title: См. ещё
description: A collection of things, people and more.
lang: ru
url: https://ru.alsosee.info
repo: https://github.com/alsosee/ru
opengraph:
  image: https://ru.media.alsosee.info/opengraph.png
  width: 1920
  height: 1080
  twitter_image: https://ru.media.alsosee.info/twitter.png
logo_shift_y: -44px
home_label: Главная
search_label: Поиск
views_label: Views
views_tooltip: Show items as icons, in a list or in columns
view_icons: Icons
view_list: List
view_columns: Columns
menu:
  - title: alsosee.info
    url: https://alsosee.info
  - title: ru.alsosee.info
    url: https://ru.alsosee.info
    logo_shift_y: -44px
label_cancel: Cancel
label_upload: Upload
