title: См. ещё
description: A collection of things, people and more.
lang: ru
url: https://ru.alsosee.info
media_host: https://ru.media.alsosee.info
repo: https://github.com/alsosee/ru
opengraph:
  image: https://ru.media.alsosee.info/opengraph.png
  width: 1920
  height: 1080
  twitter_image: https://ru.media.alsosee.info/twitter.png
logo_shift_y: -44px
home_label: Главная
search_label: Поиск
not_found_header: Не найдено
not_found_description: Запрашиваемый объект не найден.
not_found_but_description: Запрашиваемый объект не найден. Ниже показаны наиболее близкие совпадения.
views_label: Вид
views_tooltip: Показать как иконки, список или колонки
view_icons: Иконки
view_list: Список
view_columns: Колонки
menu:
  - title: alsosee.info
    url: https://alsosee.info
  - title: ru.alsosee.info
    url: https://ru.alsosee.info
    logo_shift_y: -44px
label_cancel: Отмена
label_upload: Загрузить
no_results_label: Ничего не найдено.
of_label:
and_label: и
column_name: Имя
column_kind: Вид
