name: finder

on:
  push:
    branches:
      - main
    paths:
      - _finder/**
      - .github/workflows/finder.yml
  workflow_dispatch:
  repository_dispatch:
    types: [finder]

jobs:
  finder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout finder
        uses: actions/checkout@v4
        with:
          repository: alsosee/finder
          path: finder

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        env:
          DOCKER_IMAGE: ghcr.io/alsosee/ru
        with:
          registry: ghcr.io
          username: alsosee-bot
          dockerfile: _finder/Dockerfile
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64/v8

      - name: Trigger deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN }}
          repository: alsosee/ru
          event-type: deploy
