name: main

on:
  push:
    branches:
      - main
    paths-ignore:
      - _finder/**
      - .github/workflows/finder.yml
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone info
        uses: actions/checkout@v4
        with:
          repository: alsosee/ru
          path: info
          token: ${{ secrets.TOKEN }}

      - name: Clone info state
        uses: actions/checkout@v4
        with:
          repository: alsosee/ru
          path: state
          ref: state
          token: ${{ secrets.TOKEN }}

      - name: Clone media
        uses: actions/checkout@v4
        with:
          repository: alsosee/media-ru
          path: media
          token: ${{ secrets.TOKEN }}

      - name: Run action
        uses: ./info/_finder
        with:
          info: ./info
          media: ./media
          output: ./output
          media_host: https://ru.media.alsosee.info
          search_host: https://search.alsosee.info
          search_api_key: ${{ secrets.MEILISEARCH_KEY }}
          search_index: ru
          search_master_key: ${{ secrets.MEILISEARCH_MASTER_KEY }}
          search_state: ./state/state
          ignorefile: .ignore
          # force: ${{ env.FORCE }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy output --project-name=finder-ru --branch=main --commit-dirty=true

      - name: Commit and push state
        shell: bash
        run: |
          cd state
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'gha@alsosee.info'
          git add "state"
          git commit -m "Update index state [skip ci]"
          git push origin state
